/**:
  ros__parameters:
    # -- Node Configurations --
    planning_algorithm: "astar"
    waypoints_velocity: 1.0

    # -- A* search Configurations --
    # base configs
    time_limit: 3000.0
    # robot configs
    maximum_turning_radius: 5.0
    turning_radius_size: 5
    vehicle_dimension_margin: 0.0
    # search configs
    theta_size: 12
    goal_angular_tolerance: 0.261799
    curve_weight: 1.2
    reverse_weight: 2.0
    goal_lateral_tolerance: 0.25
    goal_longitudinal_tolerance: 1.0
    # costmap configs
    obstacle_threshold: 100

    astar:
      use_back: false
      use_reeds_shepp: true
      only_behind_solutions: false
      distance_heuristic_weight: 1.0


    # vehicle characteristics for vehicle_constants_manager operation
    # when launching the whole system these parameters should not be part of this package's params
    # however to be able to run the node standalone these parameters are required
    vehicle:
      wheel_radius: 0.05 # Measured from SVL
      wheel_width: 0.27 # Measured from SVL
      wheel_base: 0.3 # Measured from SVL
      wheel_tread: 1.571 # Measured from SVL
      overhang_front: 0.1 # Measured from SVL
      overhang_rear: 0.1 # Measured from SVL
      overhang_left: 0.02 # Measured from SVL
      overhang_right: 0.02 # Measured from SVL
      vehicle_height: 0.3 # Measured from SVL
      cg_to_rear: 0.15 # Assuming it is in middle of front and rear axle centers
      tire_cornering_stiffness_front: 0.1 # Taken from AVP demo params, can't verify
      tire_cornering_stiffness_rear: 0.1 # Taken from AVP demo params, can't verify
      mass_vehicle: 5.0 # Measured from SVL
      inertia_yaw_kg_m2: 1.0  # Taken from AVP demo params, can't verify
      maximum_turning_angle_rad: 0.45
